### ISSUE TITLE
Last merges in the development branch were not resolved correctly. It is necessary that it be in a consistent state so that it passes to the master branch

### ISSUE THREAD

**Issue by stdevRulo** [stdevRulo/ISMT#9]

**Comment by stdevAntiD2ta** [comment]
The major problems for me are in the views, so this has to be assigned to the others to.

**Comment by stdevRulo** [comment]
when I created the commit, the many backend problems that did not allow the application to run were not solved, but in general it concerns us all and it needs the views to work correctly before going to the master branch
